### ISSUE TITLE
pip install json2parquet failed on mac high sierra with python3.6

### ISSUE THREAD

**Issue by whossa** [andrewgross/json2parquet#22]
pip3 install json2parquet  
Collecting json2parquet
  Using cached https://files.pythonhosted.org/packages/16/e8/9a2b6a1958f99e83ed9d7b8abe9ba277fe4a833177b334782f0aedd05877/json2parquet-0.0.22-py3-none-any.whl
Collecting pandas==0.23.3 (from json2parquet)
  Using cached https://files.pythonhosted.org/packages/d8/ba/d2c6578afca709e211ac1cd836a66a6a042f1a773a970be345d9d08be426/pandas-0.23.3-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting ciso8601 (from json2parquet)
  Using cached https://files.pythonhosted.org/packages/61/d8/e17159b6037a26e3facdfeec8750dd17312284a915c5e0da79562b982035/ciso8601-2.0.1.tar.gz
Collecting pyarrow==0.9.0 (from json2parquet)
  Using cached https://files.pythonhosted.org/packages/be/2d/11751c477e4e7f4bb07ac7584aafabe0d0608c170e4bff67246d695ebdbe/pyarrow-0.9.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/rd/g025_v1137975vy0szky7d140000gs/T/pip-install-8lnrr37_/pyarrow/setup.py", line 508, in <module>
        url="https://arrow.apache.org/"
      File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python3.6/site-packages/setuptools/dist.py", line 363, in __init__
        _Distribution.__init__(self, attrs)
      File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/usr/local/lib/python3.6/site-packages/setuptools/dist.py", line 519, in finalize_options
        ep.load()(self, ep.name, value)
      File "/private/var/folders/rd/g025_v1137975vy0szky7d140000gs/T/pip-install-8lnrr37_/pyarrow/.eggs/setuptools_scm-3.0.2-py3.6.egg/setuptools_scm/integration.py", line 23, in version_keyword
        dist.metadata.version = get_version(**value)
      File "/private/var/folders/rd/g025_v1137975vy0szky7d140000gs/T/pip-install-8lnrr37_/pyarrow/.eggs/setuptools_scm-3.0.2-py3.6.egg/setuptools_scm/__init__.py", line 135, in get_version
        parsed_version = _do_parse(config)
      File "/private/var/folders/rd/g025_v1137975vy0szky7d140000gs/T/pip-install-8lnrr37_/pyarrow/.eggs/setuptools_scm-3.0.2-py3.6.egg/setuptools_scm/__init__.py", line 77, in _do_parse
        parse_result = _call_entrypoint_fn(config, config.parse)
      File "/private/var/folders/rd/g025_v1137975vy0szky7d140000gs/T/pip-install-8lnrr37_/pyarrow/.eggs/setuptools_scm-3.0.2-py3.6.egg/setuptools_scm/__init__.py", line 40, in _call_entrypoint_fn
        return fn(config.absolute_root)
      File "/private/var/folders/rd/g025_v1137975vy0szky7d140000gs/T/pip-install-8lnrr37_/pyarrow/setup.py", line 462, in parse_version
        return version_from_scm(root)
      File "/private/var/folders/rd/g025_v1137975vy0szky7d140000gs/T/pip-install-8lnrr37_/pyarrow/.eggs/setuptools_scm-3.0.2-py3.6.egg/setuptools_scm/__init__.py", line 28, in version_from_scm
        return _version_from_entrypoint(root, "setuptools_scm.parse_scm")
      File "/private/var/folders/rd/g025_v1137975vy0szky7d140000gs/T/pip-install-8lnrr37_/pyarrow/.eggs/setuptools_scm-3.0.2-py3.6.egg/setuptools_scm/__init__.py", line 44, in _version_from_entrypoint
        for ep in iter_matching_entrypoints(config.absolute_root, entrypoint):
    AttributeError: 'str' object has no attribute 'absolute_root'

On my macOS High Sierra with version(10.13.3) and python3.6

**Comment by andrewgross** [comment]
PyArrow has issues on Mac for `0.9.0`, you will need to install `0.9.0.post1`

https://pypi.org/project/pyarrow/0.9.0.post1/

**Comment by gmr** [comment]
@andrewgross a related issue for this is the pypi package is hard-pinned to 0.9.0.  Work-around is easy, but makes it harder to just do a pip install :)  Thanks for this project btw. I was going to write something similar today to convert some data.

**Comment by andrewgross** [comment]
Yeah, unfortunately they didn't distribute the `post1` wheel as part of `0.9.0` directly.  I don't have a great solution that works in dev and prod environments.  BTW if you are looking for a CSV oriented version of this, or just more example code check out.  

https://github.com/hellonarrativ/spectrify/

There are a lot of similarities and shared code between these projects.  I have worked with the author on a few different issues.

**Comment by andrewgross** [comment]
We are on `0.0.12` now, so this should be fixed.
